version: 2.1

orbs:
  ios: wordpress-mobile/ios@dev:split-caching

workflows:
  wordpress_ios:
    jobs:
      - ios/test:
          name: build_and_test
          workspace: WordPress.xcworkspace
          scheme: WordPress
          device: iPhone XS
          ios-version: "12.1"
          # If you want to reset the CircleCI cache, increment the number in the cache prefix below
          cache-prefix: dependency-cache-v1
